### ISSUE TITLE
Adding Tags to Camel

### ISSUE THREAD

**Issue by ToniWonKanobi** [cliss/camel#31]
*Truly, less is more.*

I assume this is why Camel is the way it is&mdash;fast [first], simple, and relatively straight-forward.

I dig that.

I wouldn't want it any other way.

And yet.

**Tags**

Yes, *those*.

I know what you're thinking (you're thinking, "Eh").

I can understand.

Because *less is more*.

But here's the thing:

Camel ~~needs~~ could use tags. Tags are useful and helpful when used like [this](http://mattgemmell.com/designing-blogs-for-readers/#optional-functionality "Matt Gemmell's ideas re: keywords"), *not* necessarily like [this](https://wordpress.org/plugins/ultimate-tag-cloud-widget/screenshots/ "Tag clouds are satan"). Tags don't *have* to be associated with their oft-icky implementation.

Roger Stringer's fork has [tags](https://github.com/DataMcFly/camel/commit/31a3a9c2e89a434a6e67c3b06da3edbeb42ddd5e "Roger Stringer's Camel fork has tags"), but his is based on his own custom variables that make cribbing to your "Standard Camel" fork somewhat non-trivial.

***

Basic support would entail:

1. Basic metadata support for "Tags" (or "Keywords"&mdash;whatever you want to call it), be that via the traditional `metadataMarker`&mdash;`@@`&mdash;or via the newest metadata format in 1.5.3, e.g., `Tags:`

2. Support for `/tags` and `/tags/tag` slugs

**Comment by cliss** [comment]
I recommend using Roger's fork.

Personally, I have zero desire for tags. I don't write many posts on one theme very often, and when I do, I tend to cross-link between them heavily.

Furthermore, tagging without a database increases memory pressure on the system, as every tag, and all associated posts, will need to be kept in memory, always.

I'm not saying it'll *never* happen. But I am saying I have no intention of doing so anytime soon. Sorry.

**Comment by ToniWonKanobi** [comment]
Understood (😞). Thanks for replying :D




On November 17, 2015 at 5:30:55 AM, Casey Liss (notifications@github.com) wrote:

Closed #31.
