### ISSUE TITLE
`npm start` fails under Homebrew

### ISSUE THREAD

**Issue by chrisfinazzo** [cliss/camel#32]
Not sure if this is a real issue, or I may have missed a step configuring something, but while `node ./camel.js` starts a local server on port 5000, `npm start` implodes.

<img width="711" alt="screen shot 2016-02-08 at 6 10 35 pm" src="https://cloud.githubusercontent.com/assets/1534882/12902450/4f1b20bc-ce8f-11e5-996d-c93abc59647a.png">

**Comment by ToniWonKanobi** [comment]
What exactly are you attempting?

**Comment by cliss** [comment]
I've not personally done anything to set up for `npm start` to work. I do all my development using [Nodemon](http://nodemon.io), which I think you'll find works pretty well.

If there's some reason that doesn't work, or I'm missing your point, do let me know.

**Comment by chrisfinazzo** [comment]
Ah, I see. Installing `nodemon` into `/Camel` and _then_ doing `npm start` succeeds.

**Comment by chrisfinazzo** [comment]
is there a preferred way to configure a Camel fork? At present, I'm following along [here][], and it was...surprisingly complicated given the instructions.

[here]: https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by cliss** [comment]
Generally speaking, it's easiest to fork via the Github website.
